name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Generate secrets.toml
        run: |
          mkdir -p .streamlit
          cat <<EOF > .streamlit/secrets.toml
          [auth]
          redirect_uri = "https://streamlit-app-1098493834184.asia-northeast1.run.app/oauth2callback"
          cookie_secret = "${{ secrets.COOKIE_SECRET }}"
          client_id = "${{ secrets.CLIENT_ID }}"
          client_secret = "${{ secrets.CLIENT_SECRET }}"
          server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
          EOF

      - name: Configure Docker
        run: |
          gcloud auth configure-docker ${{ secrets.REGION }}-docker.pkg.dev --quiet

      - name: Build and Push
        run: |
          docker build -t ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.ARTIFACT_REPO }}/streamlit-app:${{ github.sha }} .
          docker push ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.ARTIFACT_REPO }}/streamlit-app:${{ github.sha }}
          
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: streamlit-app
          image: ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.ARTIFACT_REPO }}/streamlit-app:${{ github.sha }}
          region: ${{ secrets.REGION }}
          allow-unauthenticated: true
